### ISSUE TITLE
Errors out on load and doesn't provide option to save (PC saves)

### ISSUE THREAD

**Issue by TheRealPSV** [dfrood/SA2SaveUtility#4]
For PC saves, errors out on both main and Chao saves when loading, and Save is always disabled

Chao save: [SONIC2B__ALF.zip](https://github.com/dfrood/SA2SaveUtility/files/3544191/SONIC2B__ALF.zip)
Error:
```
System.ArgumentOutOfRangeException: Value of '100' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at SA2SaveUtility.ChaoSave.UpdateChao(TabControl tc, KeyValuePair`2 currentChao, Byte[] chao)
   at SA2SaveUtility.ChaoSave.GetChao()
   at SA2SaveUtility.Main.SaveIsChao()
   at SA2SaveUtility.Main.Tsmi_Open_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Main save: [SONIC2B__S01.zip](https://github.com/dfrood/SA2SaveUtility/files/3544196/SONIC2B__S01.zip)
Error:
```
System.ArgumentOutOfRangeException: Value of '100003039' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at SA2SaveUtility.MainSave.UpdateSave(TabControl tc, KeyValuePair`2 currentMain, Byte[] save)
   at SA2SaveUtility.MainSave.GetMain()
   at SA2SaveUtility.Main.SaveIsMain()
   at SA2SaveUtility.Main.Tsmi_Open_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by TheRealPSV** [comment]
Sorry for not responding sooner; I didn't realize you'd replied. I think I used a cheat mod to reach those values. Specifically it was a cheat code in the SA2 Mod Loader's Code options: http://info.sonicretro.org/SA2_Mod_Loader
